### ISSUE TITLE
Variable explorer not showing variables

### ISSUE THREAD

**Issue by ronimb** [spyder-ide/spyder-notebook#115]
This issue occurs only in my home pc, 
When i launch a console from a notebook none of the variables are displayed, 
the same goes for variables created in that same console.

So far, i've tried uninstalling and reinstalling jupyterlab and not much else.

What information do you need me to provide?

**Comment by dalthviz** [comment]
Hi @ronimb could you tell us how did you install the plugin and Spyder (pip or conda)?. Also, could you check if you are excluding variables? (you can click the tool button of the variable explorer and see if any option has been checked). Any information to replicate the issue would be really appreciated :)

**Comment by ronimb** [comment]
Hi!,
I figured you'd need more information but wasnt really sure what to provide...

I installed everything using conda, from the conda-forge repo, but this was the same way i installed spyder-notebook in my lab-pc where the variable explorer is working fine.

Is there anything else i can do to help?

**Comment by ccordoba12** [comment]
> So far, i've tried uninstalling and reinstalling jupyterlab and not much else.

Maybe Jupyterlab is interfering with our implementation. Could you uninstall it and try again?

**Comment by ronimb** [comment]
Whoops, i meant spyder-notebook,
but i do have jupyter-lab installed on this machine so i will try uninstalling it and report back (although it is also installed on my lab pc where this problem doesn't happen)

**Comment by MarkPratley** [comment]
I have this issue too:


Variables not shown in variable explorer from notebook console.

Variable explorer doesn't update when switching from another console to notebook console.

When only using a notebook console variable explorer is completely blank - i.e. no name, type, size, value columns. No icons for options or to import data etc)

windows 10

Spyder 3.2.3

python 3.5.2 - 64 bit
Qt 5.6.0
PyQt5 5.6

IPython >=4.0    :  5.1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

installed by:

conda update spyder
conda install spyder-notebook -c spyder-ide

Jupyterlab was installed and is now uninstalled.

If I click show environment variables from the notebook console i get this error, which seems related:

  File "C:\Users\markp\Anaconda2\envs\py35\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 491, in show_env
    self.dialog_manager.show(RemoteEnvDialog(env))
  File "C:\Users\markp\Anaconda2\envs\py35\lib\site-packages\spyder\utils\environ.py", line 45, in __init__
    self.setup(envdict2listdict(environ),
  File "C:\Users\markp\Anaconda2\envs\py35\lib\site-packages\spyder\utils\environ.py", line 26, in envdict2listdict
    for key in envdict:
TypeError: 'NoneType' object is not iterable

**Comment by ronimb** [comment]
Hi again,
After performing a clean re-install of anaconda, the variable explorer is now working correctly.

During the cleanup, i also removed the jupyter config filer located in c:\users\%USER%\.jupyter ,
i suspect these were related to the issue because i remember making some changes to the authentication process in the past.

**Comment by dalthviz** [comment]
Thanks for the telling us the way you manage to solve this @ronimb 👍 . @MarkPratley do you have a config file or do you have done some change for the authentication process of the notebooks?

**Comment by MarkPratley** [comment]
This has cleared itself up after a conda and spyder-notepad re-install and is now working fine.

Thanks for looking into this though

**Comment by dalthviz** [comment]
Thanks @ronimb and @MarkPratley to let us know how you guys handled this problem.

**Comment by theonesp** [comment]
Hi! I've done everything you listed in the issue and variables are still not showing on Spyder.

I have last version of spyder (3.3.0), notebook (5.6.0).

I also tried reinstalling everything.

**Comment by ccordoba12** [comment]
The latest Spyder version created an incompatibility with spyder-notebook. We'll try to fix that in the next weeks.

**Comment by theonesp** [comment]
Which Spyder version do you recommend as the stable one?
Miguel

------------------------------

  [image: MIT][image: imes]

*Miguel Ángel Armengol de la Hoz **✉* <maarmeng@mit.edu> / Research
Scientist
*MIT - Institute for Medical Engineering and Science *
*Laboratory for Computational Physiology*
MIT, E25-235- 53 Carleton St.
Cambridge, MA 02139

[image: LinkedIn logo]
<https://www.linkedin.com/in/miguelangelarmengol/?locale=en_US>

**Comment by t8ch** [comment]
> The latest Spyder version created an incompatibility with spyder-notebook. We'll try to fix that in the next weeks.

Is there news on that?

**Comment by jitseniesen** [comment]
@t8ch The incompatibility seems to have sorted itself out, or perhaps it was never really there in the first place. If you do find a problem, please let us know.

I started to look at the spyder-notebook plugin with a view to restarting development.

PS: The current version of spyder-notebook is incompatible with the beta version of Spyder 4.

**Comment by ccordoba12** [comment]
@t8ch, that problem will be fixed when we release Spyder 4. It can't be solved here.

**Comment by lwbaqueros** [comment]
That's good news that you are going to release 4.0 with spyder-notebook support. thnak you.

**Comment by chandrika-gavireddy** [comment]
Hi, Is any new thread opened for the issue
Im using spyder 4.0.1 version
still im unable to view variables in variable explorer

**Comment by dalthviz** [comment]
@chandrika-gavireddy maybe this is caused since, for the moment, you need to update the Variable Explorer (with the refresh button ↺) or press `Enter/Return` inside the console connected with the notebook (the one that is created when you click the `Open Console` option from the menu) to show the variables created?:

![notebook](https://user-images.githubusercontent.com/16781833/72443260-fb9b8580-377b-11ea-9e75-10ff4488d5e7.gif)

**Comment by chandrika-gavireddy** [comment]
Thanks a lot

**Comment by ikeszvpvb9ye** [comment]
Good day. The problem is still relevant. Here are the steps to reproducing the problem (checked twice with the complete removal of Anaconda and cleaning user folders and the registry)
1. Install Anaconda3-2019.10-Windows-x86_64
2. Connecting conda-forge and spyder-ide channels
3. Automatic update of anaconda navigator to 1.9.12
4. Run the following commands
```
conda update -n root conda
conda update --all (spyder is updated to 4.0.0rc1)
conda install -c spyder-ide spyder-notebook spyder-unittest spyder-terminal spyder-reports (spyder is updated to 4.0.1)
conda install -c spyder-ide spyder-line-profiler spyder-memory-profiler
```
kite installation on first start

as a result, we have a configuration
Name Version Build Channel
jupyter 1.0.0 py_2 conda-forge
jupyter_client 6.0.0 py_0 conda-forge
jupyter_console 6.0.0 py_0 conda-forge
jupyter_core 4.6.3 py37_0 conda-forge
jupyterlab 2.0.0 py_1 conda-forge
jupyterlab_server 1.0.6 py_0 conda-forge
spyder 4.0.1 py37_3 conda-forge
spyder-kernels 1.8.1 py37_1 conda-forge
spyder-line-profiler 0.2.0 py_0 spyder-ide
spyder-memory-profiler 0.2.0 py37_1 spyder-ide
spyder-notebook 0.2.2 py_0 spyder-ide
spyder-reports 0.1.1 py37_1001 conda-forge
spyder-terminal 0.2.4 py37_0 spyder-ide
spyder-unittest 0.4.0 py_0 spyder-ide
Full configuration in the file "conda list.txt"
[conda list.txt](https://github.com/spyder-ide/spyder-notebook/files/4271814/conda.list.txt)

As a result, in Spyder we get such a picture
![0002](https://user-images.githubusercontent.com/52958114/75626752-35650600-5bdb-11ea-9e4e-af9cd0aa437d.png)
![0003](https://user-images.githubusercontent.com/52958114/75626754-3a29ba00-5bdb-11ea-84e4-c6cbab8921f1.png)
![0004](https://user-images.githubusercontent.com/52958114/75626755-3dbd4100-5bdb-11ea-99e5-a4d9a674c90e.png)
![0005](https://user-images.githubusercontent.com/52958114/75626757-401f9b00-5bdb-11ea-8673-b96bdd248ba5.png)

**Comment by ikeszvpvb9ye** [comment]
Recommendations from the comment https://github.com/spyder-ide/spyder-notebook/issues/115#issuecomment-574694333 do not work

**Comment by ikeszvpvb9ye** [comment]
The problem was resolved by changing the file path and the name of the notebook. The specifics of os.getcwd () on Windows with Cyrillic characters. This can be seen from the Anaconda console logs.
The question about os.getcwd () is asked at https://github.com/spyder-ide/spyder-notebook/issues/244
