### ISSUE TITLE
Be more robust when starting notebook

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#157]
From Gitter: "I also think we should start the notebook in a more robust way. [Here](https://github.com/spyder-ide/spyder-notebook/blob/master/spyder_notebook/utils/nbopen.py#L58) we assume the `jupyter` command is in your PATH, but we could detect if that's true or not before doing it"

**Comment by ccordoba12** [comment]
Another option would be to create a Python script that starts the notebook programatically (instead of passing options to `jupyter notebook`). The main class to do that is [NotebookApp](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L560), I think.

Then we could start the notebook with something like:

```python
subprocess.Popen([sys.executable, 'nb_start.py'])
```

**Comment by ccordoba12** [comment]
#141 is also related to this. So I'd really prefer that we'd follow my last suggestion.

**Comment by jitseniesen** [comment]
Do you have something like this PR in mind? It does not seem to require a script.

**Comment by ccordoba12** [comment]
I was thinking to use a script so that the notebook server can be started in the background with `subprocess`. What are you thinking to solve this issue?

**Comment by ccordoba12** [comment]
Sorry, I didn't see your referenced PR. I'm looking at it right now.
