### ISSUE TITLE
Variable explorer not showing variables. Spyder 4.0.1. Specifics of os.getcwd() on Windows working with Cyrillic characters

### ISSUE THREAD

**Issue by ikeszvpvb9ye** [spyder-ide/spyder-notebook#244]
## Variable explorer not showing variables. Spyder 4.0.1

**What steps will reproduce the problem?**

1. See steps to reproducing the problem in comment https://github.com/spyder-ide/spyder-notebook/issues/115#issuecomment-593098522

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
See screenshots in coment https://github.com/spyder-ide/spyder-notebook/issues/115#issuecomment-593098522

## Versions and main components

* Spyder Version: 4.0.1
spyder-kernels            1.8.1     
spyder-line-profiler      0.2.0            
spyder-memory-profiler    0.2.0    
spyder-notebook           0.2.2    
spyder-reports            0.1.1      
spyder-terminal           0.2.4 
spyder-unittest           0.4.0  
* Python Version: 3.7.6
* Qt Version: 5.12.5
* PyQt Version: 5.12.3
* Jupyter Notebook Version:
jupyter                   1.0.0   
jupyter_client            6.0.0 
jupyter_console           6.0.0             
jupyter_core              4.6.3 
jupyterlab                2.0.0   
jupyterlab_server         1.0.6 
* Operating system: Win10 x64 1909
see more [conda list.txt](https://github.com/spyder-ide/spyder-notebook/files/4271849/conda.list.txt)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  19.0.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  2.4.3 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by ikeszvpvb9ye** [comment]
Recommendations from the comment https://github.com/spyder-ide/spyder-notebook/issues/115#issuecomment-574694333 do not work

**Comment by jitseniesen** [comment]
It works for me. When I switch to the console coupled to the notebook, the variable explorer displays the variables in the notebook. But for you, the display of the variable explorer does not seem to change. Unfortunately, I don't know why.

Try running Spyder with `spyder --debug-info verbose` from the Anaconda prompt and see whether something relevant appears in the debug info when you switch console.

Also, try installing Spyder from the original Conda channel instead of `conda-forge`.

**Comment by ikeszvpvb9ye** [comment]
@jitseniesen when I switching consoles, I see the following messages
For standard console
`2020-03-01 18:51:17,943 [DEBUG] [traitlets] -> handle_msg[6b53f8925bd311ea838ea01d48d20fce]({'header': {'msg_id': '48e413cd-15c3336af61f49d8fac61edc_54', 'msg_type': 'comm_msg', 'username': 'username', 'session': '48e413cd-15c3336af61f49d8fac61edc', 'date': datetime.datetime(2020, 3, 1, 15, 51, 17, 931999, tzinfo=tzutc()), 'version': '5.3'}, 'msg_id': '48e413cd-15c3336af61f49d8fac61edc_54', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': '1e1d83a8-2351470b04ba2ed86d9ad563_19', 'msg_type': 'comm_msg', 'username': 'username', 'session': '1e1d83a8-2351470b04ba2ed86d9ad563', 'date': datetime.datetime(2020, 3, 1, 15, 51, 17, 926005, tzinfo=tzutc()), 'version': '5.3'}, 'metadata': {}, 'content': {'data': {'spyder_msg_type': 'remote_call_reply', 'content': {'is_error': False, 'call_id': '35c7b49c8aa24f528c66ee56c75536ca', 'call_name': 'get_cwd'}, 'pickle_protocol': 4, 'python_version': '3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)]'}, 'comm_id': '6b53f8925bd311ea838ea01d48d20fce'}, 'buffers': [<memory at 0x000002302BBDAB88>]})`
For notebook console
`2020-03-01 18:51:10,520 [DEBUG] [spyder_kernels.comms.commbase] -> Call to unconnected comm: get_cwd`
full log here 
[spyder --debug-info verbose.txt](https://github.com/spyder-ide/spyder-notebook/files/4272043/spyder.--debug-info.verbose.txt)

**Comment by ikeszvpvb9ye** [comment]
@jitseniesen get_cwd - There was an idea that the problem could be in the path to the selected file. I removed from the path to the file and from its name Cyrillic characters and variables explorer now work. Is this the specifics of os.getcwd () on Windows, or can it be somehow supported by Spyder?

**Comment by ccordoba12** [comment]
If notebooks are not working for you (according to #246), then I don't know how you expect the Variable Explorer works for them.

**Comment by ikeszvpvb9ye** [comment]
@ccordoba12 we managed to solve the problem https://github.com/spyder-ide/spyder-notebook/issues/246 by the firewall settings, some of the bat files were in the "Weak restrictions" group, therefore the Jupiter kernel did not start automatically, but that does not mean that it could not be started manually (shortcut from the desktop or from Anaconda until Spyder started)

**Comment by ikeszvpvb9ye** [comment]
This ticket is obtained about the specifics of os.getcwd() on Windows working with Cyrillic characters. This can be seen from the Anaconda console logs.

**Comment by jitseniesen** [comment]
@ikeszvpvb9ye Thanks, that looks very helpful. When I try to connect to the console connected to a notebook in a directory with Cyrillic characters on Linux, everything works fine. However, I am not surprised if it does not work under Windows. I will try to reproduce it on Windows but that may take a while.

**Comment by jitseniesen** [comment]
I am afraid I was not able to reproduce this. I did a fresh install of Spyder from the official Anaconda channel and of the notebook plugin on Windows 10 and the variable explorer does show all the variables of the notebook. I tried to give the notebook and the directory it is in, names with Cyrillic and Chinese characters. The only suggestion I can give at this point is to use the default channel instead of `conda-forge` (and make sure you hit the refresh button on the variable explorer).

**Comment by ccordoba12** [comment]
> and make sure you hit the refresh button on the variable explorer

So now there's no need to open a new console connected to the notebook?

**Comment by jitseniesen** [comment]
> So now there's no need to open a new console connected to the notebook?

No, you still need to do that.

**Comment by ikeszvpvb9ye** [comment]
The problem does not reproduce in the 4.1.2 version

**Comment by bhaskatripathi** [comment]
"_> I am afraid I was not able to reproduce this. I did a fresh install of Spyder from the official Anaconda channel and of the notebook plugin on Windows 10 and the variable explorer does show all the variables of the notebook. I tried to give the notebook and the directory it is in, names with Cyrillic and Chinese characters. The only suggestion I can give at this point is to use the default channel instead of `conda-forge` (and make sure you hit the refresh button on the variable explorer)."_

Everyone tries to hit the refresh button before logging such issues. However, restarting Spyder resolved the problem for me. It keeps occurring randomly when I choose open Spyder with "Run as Administrator".
