### ISSUE TITLE
After integration Spyder app is not working

### ISSUE THREAD

**Issue by jagadeeshvenkatesh** [spyder-ide/spyder-notebook#357]
## Description of your problem

**What steps will reproduce the problem?**

1. use the command pip install jupyter-notebook --user
2. 
3. 

**What is the expected output? What do you see instead?**
expected output - able to work in spyder app
Output - unable to open spyder app

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version:  
* Python Version:
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version:
* Operating system: windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by mmagnuski** [comment]
@jagadeeshvenkatesh I am not the maitainer of this repo, so I will not be able to help, but you provide too little information so that someone could actuallyh help you. Please specify what you mean by "unable to open spyder app" - how do you try to open it and what errors do you get? For example try running `spyder` command in the terminal and paste here the error that is produced.
Also fill the "dependencies" part of the issue template by following the instruction you see there.

**Comment by jitseniesen** [comment]
Sorry that nobody picked this up. Given that this was many years and versions ago, it will probably be impossible to find out what went wrong. If you still see this with a modern version of the plugin, please open a new issue.
