### ISSUE TITLE
Spyder notebook plugin download so slow

### ISSUE THREAD

**Issue by Dongxy1** [spyder-ide/spyder-notebook#387]
## Description of your problem

Hi, I use conda install spyder-notebook -c spyder-ide in the shell to install the notebook plugin to spyder, my system is macos. Why it takes such a long time downloading? Is there any other methods to install?

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version: 4.2.5
* Python Version: 3.8

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Hey @Dongxy1, thanks for reporting. You can't install Spyder-notebook in your base environment. Instead, you need to run the following commands to successfully do it:

    conda create -n spyder-env -c conda-forge spyder-notebook
    conda activate spyder-env
    spyder

**Comment by ccordoba12** [comment]
>  Is this because of the version of my spyder?

Yes, it's because of your older version.

> The spyder IDE version is 5.4.0. How can I fix this problem?

I think you need now to uninstall and reinstall Anaconda again. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to that correctly.

**Comment by Dongxy1** [comment]
> > Is this because of the version of my spyder?
> 
> Yes, it's because of your old version.
> 
> > The spyder IDE version is 5.4.0. How can I fix this problem?
> 
> I think you need now to uninstall and reinstall Anaconda again. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to that correctly.

Can I install the specific version via Anaconda Navigator? To be honest, I have Anaconda on my computer, but I still download the Spyder from the standalone installer, after that, the spyder in Anaconda was disappeared. Can I still using Anaconda to install the specific version? Many thanks!

**Comment by ccordoba12** [comment]
The problem is that you used pip to update Spyder in Anaconda, which basically broke it. And now you need to reinstall it.

Regarding the standalone installer, that's the safest way to install Spyder, but it won't allow you to use Spyder-notebook because it doesn't come with it. That's because this plugin is in a beta state and not ready for the general public.

Bottom line is this: after reinstalling Anaconda, please run the following commands to have Spyder-notebook:

    conda create -n spyder-env -c conda-forge spyder=5.3.3 spyder-notebook
    conda activate spyder-env 
    spyder

Then follow the instructions in our documentation to connect this Spyder to your main installation:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment
