### ISSUE TITLE
spyder-notebook option is not visible

### ISSUE THREAD

**Issue by andrew-hyde** [spyder-ide/spyder-notebook#428]
## Description of your problem
After downloading spyder-notebook and restarting, the notebook option is not visible. It might be the version of the notebook, as Anaconda says there is a newer version available (see image), but it doesn't update. Please help. Has anyone experienced this lately?

**What steps will reproduce the problem?**
1. install spyder notebook with "conda install spyder-notebook -c conda-forge"
2. restart Spyder
3. View > Panes

**What is the expected output? What do you see instead?**
The notebook tab is not visible under View > Panes

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
![Screenshot 2023-06-28](https://github.com/spyder-ide/spyder-notebook/assets/79991982/6db1f88a-05c1-41c7-93a1-f7bb5283a862)

## Versions and main components
* Spyder Version: 5.4.1
* Python Version: 3.10
* Qt Version: 5.4.2
* PyQt Version: 5.15.7
* Jupyter Notebook Version: 6.5.4
* Operating system: Windows 11 Pro

**Comment by jitseniesen** [comment]
Hi, I am not sure what is happening. I don't use Anaconda Navigator, so I don't know whether I am interpreting your screenshot correctly, but it seems to say that you have version 0.1.4 of spyder-notebook installed. That is a very old version which is not compatible with Spyder 5, so that would explain why you don't see the Notebook pane.

To help me figure out what is going on, can you please run the command "conda list spyder-notebook"? This should display the version of spyder-notebook; if that is indeed 0.1.4 then we have found why you don't see the Notebook pane.

Of course, the real question is, why did the system install this old version. To find out, please run the command "conda install spyder-notebook -c conda-forge" again and show the output. You can specify the latest version of spyder-notebook by using the command "conda install spyder-notebook=0.4.1 -c conda-forge"; this will also update Spyder itself.

**Comment by jitseniesen** [comment]
Closing due to lack of reply.
